services:
  - type: web
    name: melbetblog-web
    env: node
    buildCommand: "npm install && npx prisma db push && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:MelbetPass123!@db.jwwyozyfvslrgykigwws.supabase.co:5432/postgres"
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: "https://jwwyozyfvslrgykigwws.supabase.co"
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3d3lvenlmdnNscmd5a2lnd3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTMwNTEsImV4cCI6MjA3MjU2OTA1MX0.QEOCVO_yYC92SGitOSHjNlXzS9wgH48UBJXA2_bYXio"
